<a href="https://colab.research.google.com/github/sandesh2059/ML/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Single dimensional array
```
this is formatted as code
```



In [8]:
import numpy as np

In [9]:
#create an array eith all the elements to be zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
#create an array with all elements 1
np.ones(5)

array([1., 1., 1., 1., 1.])

In [11]:
#creating an array of size 10 with all elements 3
np.full(10, 3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [12]:
np.array([1, 2, 3 , 4, 5])

array([1, 2, 3, 4, 5])

In [14]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [15]:
#create an array with evenly spaced numbers within a specified range
np.linspace(0, 100, 10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

### Multidimensional array

In [16]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
a[0,1]=20
a

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [33]:
a[2] = [1, 1, 1]
a

array([[ 1, 20,  2],
       [ 4,  5,  2],
       [ 1,  1,  1]])

In [34]:
a[:, 2] = [2, 2, 2]
a

array([[ 1, 20,  2],
       [ 4,  5,  2],
       [ 1,  1,  2]])

In [35]:
np.full((3,3),10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

### Randomly generated array


-Numpy can create arrays filled with random numbers
-to ensure the reproducibility, you can seta seed using ```np.random.seed()```. it will generate the exact same random numbers for each executions.
-if you remove or change the seed values, the sequence of random numbers will be changed

In [36]:
np.random.rand(5)

array([0.63404377, 0.9110107 , 0.21078738, 0.90880317, 0.07349373])

In [39]:
np.random.seed(80)
np.random.rand(5)

array([0.52191572, 0.69940637, 0.26986897, 0.67448187, 0.90807208])

In [42]:
np.random.randn(5, 2)

array([[-2.84565624,  0.7707567 ],
       [ 0.3216396 ,  0.96861342],
       [-0.747884  ,  0.05059121],
       [-1.58015636, -0.14370414],
       [-0.94933032,  0.07017044]])