<a href="https://colab.research.google.com/github/sandesh2059/ML/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Single dimensional array
```
this is formatted as code
```



In [ ]:
import numpy as np

In [ ]:
#create an array eith all the elements to be zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
#create an array with all elements 1
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
#creating an array of size 10 with all elements 3
np.full(10, 3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [ ]:
np.array([1, 2, 3 , 4, 5])

array([1, 2, 3, 4, 5])

In [ ]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
#create an array with evenly spaced numbers within a specified range
np.linspace(0, 100, 10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

### Multidimensional array

In [ ]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a[0,1]=20
a

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [ ]:
a[2] = [1, 1, 1]
a

array([[ 1, 20,  2],
       [ 4,  5,  2],
       [ 1,  1,  1]])

In [ ]:
a[:, 2] = [2, 2, 2]
a

array([[ 1, 20,  2],
       [ 4,  5,  2],
       [ 1,  1,  2]])

In [ ]:
np.full((3,3),10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

### Randomly generated array


-Numpy can create arrays filled with random numbers
-to ensure the reproducibility, you can seta seed using ```np.random.seed()```. it will generate the exact same random numbers for each executions.
-if you remove or change the seed values, the sequence of random numbers will be changed

In [ ]:
np.random.rand(5)

array([0.63404377, 0.9110107 , 0.21078738, 0.90880317, 0.07349373])

In [ ]:
np.random.seed(80)
np.random.rand(5)

array([0.52191572, 0.69940637, 0.26986897, 0.67448187, 0.90807208])

In [ ]:
np.random.randn(5, 2)

array([[-2.84565624,  0.7707567 ],
       [ 0.3216396 ,  0.96861342],
       [-0.747884  ,  0.05059121],
       [-1.58015636, -0.14370414],
       [-0.94933032,  0.07017044]])

In [3]:
### day 2
import numpy as np

In [6]:
a=np.arange(5)

In [7]:
a


array([0, 1, 2, 3, 4])

In [8]:
b=(10+(a*2))
b

array([10, 12, 14, 16, 18])

In [9]:
#comparison operation
a*b

array([ 0, 12, 28, 48, 72])

In [10]:
a >=2

array([False, False,  True,  True,  True])

In [11]:
a > b

array([False, False, False, False, False])

In [12]:
#summarizing of the data
#numpy provides functions for summarizing array data
a

array([0, 1, 2, 3, 4])

In [13]:
a.std()

1.4142135623730951

In [14]:
#find min, max and use sum of array
a.min()

0

In [15]:
a.max()

4